"""Add hosting fields

Revision ID: 1eaa04841c0d
Revises: 8b6ca8475568
Create Date: 2025-12-30 12:43:30.367800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1eaa04841c0d'
down_revision = '8b6ca8475568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Modify events table first to remove FKs and add PK
    with op.batch_alter_table('events', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        # batch_op.add_column(sa.Column('banner_image', sa.String(length=255), nullable=True))
        # batch_op.add_column(sa.Column('media_url', sa.String(length=255), nullable=True))
        # batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        # batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        # batch_op.add_column(sa.Column('media_type', sa.Enum('NONE', 'AUDIO', 'VIDEO', name='mediatype'), nullable=False, server_default='NONE'))
        # batch_op.add_column(sa.Column('host_status', sa.Enum('NOT_STARTED', 'HOSTING', 'PAUSED', 'ENDED', name='hoststatus'), nullable=False, server_default='NOT_STARTED'))
        # batch_op.add_column(sa.Column('hosted_by', sa.Integer(), nullable=True))
        # batch_op.add_column(sa.Column('stream_started_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('LIVE', 'UPCOMING', 'MISSED'),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('events_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['hosted_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_column('event_id')
        batch_op.drop_column('event_date')
        batch_op.drop_column('college_id')
        batch_op.drop_column('event_time')

    op.drop_table('suggestions')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('admins')
    op.drop_table('participation')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('pin'))

    op.drop_table('students')
    op.drop_table('notifications')
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('college_code'))

    op.drop_table('colleges')

    # Now create tables that reference events.id
    op.create_table('event_participants',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', mysql.TIME(), nullable=True))
        batch_op.add_column(sa.Column('college_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('event_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('events_ibfk_1'), 'colleges', ['college_id'], ['college_id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('LIVE', 'UPCOMING', 'MISSED'),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('stream_started_at')
        batch_op.drop_column('hosted_by')
        batch_op.drop_column('host_status')
        batch_op.drop_column('media_type')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('media_url')
        batch_op.drop_column('banner_image')
        batch_op.drop_column('id')

    op.create_table('colleges',
    sa.Column('college_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('college_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('college_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('college_code'), ['college_code'], unique=True)

    op.create_table('notifications',
    sa.Column('notification_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.college_id'], name=op.f('notifications_ibfk_1')),
    sa.PrimaryKeyConstraint('notification_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('students',
    sa.Column('student_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pin', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mobile_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('college_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.college_id'], name='students_ibfk_1'),
    sa.PrimaryKeyConstraint('student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('pin'), ['pin'], unique=True)

    op.create_table('participation',
    sa.Column('participation_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name=op.f('participation_ibfk_1')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('participation_ibfk_2')),
    sa.PrimaryKeyConstraint('participation_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admins',
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('college_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.college_id'], name=op.f('admins_ibfk_1')),
    sa.PrimaryKeyConstraint('admin_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('suggestions',
    sa.Column('suggestion_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'), server_default=sa.text("'PENDING'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('college_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('suggestions_ibfk_1')),
    sa.PrimaryKeyConstraint('suggestion_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('reviews')
    op.drop_table('event_participants')
    # ### end Alembic commands ###
