"""add_radio_timer_fields

Revision ID: 2b4374301c64
Revises: 9f9afa570417
Create Date: 2026-01-23 23:38:19.565188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4374301c64'
down_revision = '9f9afa570417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_resumed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('accumulated_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radios', schema=None) as batch_op:
        batch_op.drop_column('accumulated_duration')
        batch_op.drop_column('last_resumed_at')

    # ### end Alembic commands ###
