"""Add audio_url to college updates

Revision ID: 852592960454
Revises: b14c5ce7f847
Create Date: 2026-01-19 11:12:56.548018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '852592960454'
down_revision = 'b14c5ce7f847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('applicants_count', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_link', sa.String(length=500), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('college_update_comments')
    with op.batch_alter_table('college_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(length=500), nullable=True))
        batch_op.drop_index(batch_op.f('idx_college_update_created_at'))
        batch_op.create_index(batch_op.f('ix_college_updates_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_podcast_scheduled_time'))
        batch_op.drop_index(batch_op.f('idx_podcast_status'))
        batch_op.create_index(batch_op.f('ix_podcasts_scheduled_start_time'), ['scheduled_start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcasts_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'STUDENT', 'MAIN_ADMIN'),
               type_=sa.Enum('MAIN_ADMIN', 'ADMIN', 'STUDENT', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'STUDENT'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('MAIN_ADMIN', 'ADMIN', 'STUDENT', name='userrole'),
               type_=mysql.ENUM('ADMIN', 'STUDENT', 'MAIN_ADMIN'),
               existing_nullable=False,
               existing_server_default=sa.text("'STUDENT'"))

    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcasts_status'))
        batch_op.drop_index(batch_op.f('ix_podcasts_scheduled_start_time'))
        batch_op.create_index(batch_op.f('idx_podcast_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_podcast_scheduled_time'), ['scheduled_start_time'], unique=False)

    with op.batch_alter_table('college_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_college_updates_created_at'))
        batch_op.create_index(batch_op.f('idx_college_update_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('audio_url')

    op.create_table('college_update_comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('update_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['update_id'], ['college_updates.id'], name=op.f('college_update_comments_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('college_update_comments_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('placements')
    # ### end Alembic commands ###
