"""Add media_type to college_updates

Revision ID: 9f9afa570417
Revises: 852592960454
Create Date: 2026-01-19 11:24:52.679619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f9afa570417'
down_revision = '852592960454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=20), nullable=False))
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
